import {
  FiGrid,
  FiMessageCircle,
  FiPackage,
  FiTool,
  FiShield,
  FiSliders,
  FiSettings,
  FiBell,
  FiPlus,
  FiMinus,
  FiX,
  FiCheck,
  FiEdit2,
  FiTrash2,
  FiCopy,
  FiSearch,
  FiSend,
  FiTruck,
  FiClock,
  FiUser,
  FiAlertTriangle,
  FiZap,
  FiShoppingBag,
  FiRefreshCw,
  FiGlobe,
  FiArrowRight,
  FiSmartphone,
  FiCreditCard,
  FiTag,
  FiBookOpen,
  FiSun,
  FiMoon,
  FiMonitor,
  FiUsers,
  FiBarChart2,
  FiDollarSign,
  FiArchive,
  FiStar,
  FiHeart,
  FiHome,
  FiShoppingCart,
  FiLayers,
  FiBriefcase,
  FiMenu,
} from "react-icons/fi";
import { LuBot, LuSparkles, LuHand, LuRocket, LuLanguages, LuWandSparkles } from "react-icons/lu";
import { FaWhatsapp } from "react-icons/fa6";
import { SiAirtel, SiWhatsapp, SiVisa, SiMastercard } from "react-icons/si";
import type { IconType } from "react-icons";

const MAP: Record<string, IconType> = {
  grid: FiGrid,
  bot: LuBot,
  chat: FiMessageCircle,
  box: FiPackage,
  wrench: FiTool,
  shield: FiShield,
  sliders: FiSliders,
  gear: FiSettings,
  bell: FiBell,
  plus: FiPlus,
  minus: FiMinus,
  x: FiX,
  check: FiCheck,
  edit: FiEdit2,
  trash: FiTrash2,
  copy: FiCopy,
  search: FiSearch,
  send: FiSend,
  truck: FiTruck,
  clock: FiClock,
  user: FiUser,
  users: FiUsers,
  alert: FiAlertTriangle,
  zap: FiZap,
  store: FiShoppingBag,
  shop: FiShoppingBag,
  refresh: FiRefreshCw,
  globe: FiGlobe,
  hand: LuHand,
  arrow: FiArrowRight,
  spark: LuSparkles,
  wand: LuWandSparkles,
  phone: FiSmartphone,
  whatsapp: FaWhatsapp,
  wa: FaWhatsapp,
  card: FiCreditCard,
  credit: FiCreditCard,
  tag: FiTag,
  book: FiBookOpen,
  rocket: LuRocket,
  sun: FiSun,
  moon: FiMoon,
  monitor: FiMonitor,
  languages: LuLanguages,
  lang: LuLanguages,
  chart: FiBarChart2,
  dollar: FiDollarSign,
  archive: FiArchive,
  star: FiStar,
  heart: FiHeart,
  home: FiHome,
  cart: FiShoppingCart,
  layers: FiLayers,
  briefcase: FiBriefcase,
  menu: FiMenu,
  airtel: SiAirtel,
  visa: SiVisa,
  mastercard: SiMastercard,
  // brand aliases
  siWhatsapp: SiWhatsapp,
  faWhatsapp: FaWhatsapp,
};

export function Icon({
  name,
  size = 18,
  className,
  title,
}: {
  name: string;
  size?: number;
  className?: string;
  title?: string;
}) {
  const Comp = MAP[name];
  if (!Comp) return null;
  return <Comp size={size} className={className} title={title} aria-hidden={title ? undefined : true} />;
}

// Re-export for direct use if needed
export { FiGrid, FiMessageCircle, FiPackage, FiShield, FiSettings, LuBot, LuSparkles, LuHand, FaWhatsapp, SiWhatsapp, SiAirtel, SiVisa };
